name: CodeCoverage

on:
  push:
    paths:
      - "**.ts"
    branches: [master]
  pull_request:
    paths:
      - "**.ts"
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Generate Coverage
        run: |
          npm ci
          npm run coverage
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
