name: Unit Tests

on:
  push:
    paths:
      - "**.ts"
    branches: [master]
  pull_request:
    paths:
      - "**.ts"
    branches: [master]

jobs:
  unitTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run unit tests
        run: |
          npm ci
          npm test
        env:
          CI: true
